config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pages
  root 'pages#home'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
# frozen_string_literal: true

class Page < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 4 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# controller to respond to the request from view
class PagesController < ApplicationController
  def home
  end
  
  def index
    @pages = Page.order(:position)
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
  @page = Page.new  
  end

  def edit
    @page = Page.find(params[:id])
  end

  def create
    @page = Page.new(page_params)
    if @page.save
      UserMailer.send_page(@page).deliver
      redirect_to @page
    else
      render 'new'
    end
  end

  def update
    @page = Page.find(params[:id])

    if @page.update(page_params)
      redirect_to pages_path
    else
      render 'edit'
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    redirect_to pages_path
  end

  private

  def page_params
    params.require(:page).permit(:title, :content)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Book
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      .notice = notice 
      .alert = alert 
      = yield

app/views/pages/_form.slim
= form_with scope: :page, url: pages_path, local: true do |form| 
	= form.label :title
	br
	= form.text_field :title 
	br
	br
	= form.label :content 
	br
	= form.text_area :content
	br
	= form.submit 

app/views/pages/edit.slim
h1 Editing page
= render 'form'
br
= link_to 'Back', pages_path 

app/views/pages/home.slim
- if user_signed_in?
  	= link_to 'sign_out', destroy_user_session_path, method: :delete
- else
  	= link_to 'sign_up', new_user_registration_path
  	br
  	= link_to 'sign_in', new_user_session_path

app/views/pages/index.slim
h1 Listing pages

= link_to 'New page', new_page_path
 
table class="table table-dark"
  tr
    th Title
    th Content
    th colspan='3' 
		
  -@pages.each do |page|
    tr
      td = page.title 
      td = page.content 
      td = link_to 'Show', page_path(page) 
      td = link_to 'Edit', edit_page_path(page)
      td = link_to 'Delete', pages_path, method: :destroy, data: {confirm: 'Are you sure?'}
			
  

app/views/pages/new.slim
h1 Creating new page
= render 'form'
br
= link_to 'Back', pages_path 

app/views/pages/show.slim
strong Title:
= @page.title 

strong Content:
= @page.content
= link_to 'Back', pages_path

app/views/welcome/index.html.slim
h1 Welcome to pages
br
= link_to 'page collections', pages_path 